language: node_js
node_js: '0.10'
sudo: false
cache:
  directories:
  - bower_components
  - node_modules

install:
- npm install
- node_modules/.bin/bower install

script:
- node_modules/.bin/coffeelint script
